## Logistic regression with Scikit-learn

ในบทนี้เราจะทำการประมาณการข้อมูล ซึ่งข้อมูลของเราในที่นี้คือ ปัจจัยที่ทำให้เกิดเบาหวาน หากคุณเป็นเบาหวาน y=1 แต่ถ้าไม่เป็นเบาหวาน y=0 เราจะใช้ scikit-learn ในการประมาณการ โดยจะมีการแบ่งข้อมูลออกเป็น training set และ testing set เพื่อที่จะดูว่า model ที่เราใช้ แม่นยำพอที่จะไปใช้กับข้อมูลอื่นได้หรือไม่ และเราจะตรวจสอบความแม่นยำของข้อมูลโดยใช้ confusion matrix 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
data=pd.read_csv('C:\\Users\\LENOVO\\Desktop\\files for example\\diabetes2.csv')
data.sample(20)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
427            1      181             64             30      180  34.1   
588            3      176             86             27      156  33.3   
728            2      175             88              0        0  22.9   
30             5      109             75             26        0  36.0   
686            3      130             64              0        0  23.1   
288            4       96             56             17       49  20.8   
515            3      163             70             18      105  31.6   
43             9      171            110             24      240  45.4   
569            0      121             66             30      165  34.3   
607            1       92             62             25       41  19.5   
244            2      146             76             35      194  38.2   
439            6      107             88              0        0  36.8   
279            2      108             62             10      278  25.3   
699            4      118             70              0        0  44.5   
484            0      145              0              0        0  44.2   
437            5      147             75              0        0  29.9   
349            5        0             80             32        0  41.0   
757            0      123             72              0        0  36.3   
11            10      168             74              0        0  38.0   
638            7       97             76             32       91  40.9   

     DiabetesPedigreeFunction  Age  Outcome  
427                     0.328   38        1  
588                     1.154   52        1  
728                     0.326   22        0  
30                      0.546   60        0  
686                     0.314   22        0  
288                     0.340   26        0  
515                     0.268   28        1  
43                      0.721   54        1  
569                     0.203   33        1  
607                     0.482   25        0  
244                     0.329   29        0  
439                     0.727   31        0  
279                     0.881   22        0  
699                     0.904   26        0  
484                     0.630   31        1  
437                     0.434   28        0  
349                     0.346   37        1  
757                     0.258   52        1  
11                      0.537   34        1  
638                     0.871   32        1

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
Pregnancies                 768 non-null int64
Glucose                     768 non-null int64
BloodPressure               768 non-null int64
SkinThickness               768 non-null int64
Insulin                     768 non-null int64
BMI                         768 non-null float64
DiabetesPedigreeFunction    768 non-null float64
Age                         768 non-null int64
Outcome                     768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [4]:
data.Outcome.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [5]:
y = data.Outcome.values
x_data = data.drop(['Outcome'], axis = 1)

In [6]:
x = (x_data - np.min(x_data)) / (np.max(x_data) - np.min(x_data)).values #คือการทำให้ข้อมูลไม่มีหน่วย  และปรับค่าของข้อมูลทั้งหมดให้อยู่ระหว่าง 0-1

In [7]:
from patsy import dmatrices
import statsmodels.api as sm

In [8]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [10]:
y, x  = dmatrices('Outcome ~ Pregnancies + Glucose + BloodPressure + SkinThickness + Insulin + BMI + DiabetesPedigreeFunction + Age', data=data, return_type = 'dataframe')

In [12]:
model = sm.Logit(y, x).fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.470993
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  768
Model:                          Logit   Df Residuals:                      759
Method:                           MLE   Df Model:                            8
Date:                Fri, 13 Mar 2020   Pseudo R-squ.:                  0.2718
Time:                        14:26:00   Log-Likelihood:                -361.72
converged:                       True   LL-Null:                       -496.74
                                        LLR p-value:                 9.652e-54
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                   -8.4047      0.717    -11.728      0.000      -9.809      -7.000
Pregnancies                  0.1232      0.032      3.840      0.000       0.060       0.186
Glucose                      0.0352      0.004      9.481      0.000       0.028       0.042
BloodPressure               -0.0133      0.005     -2.540      0.011      -0.024      -0.003
SkinThickness                0.0006      0.007      0.090      0.929      -0.013       0.014
Insulin                     -0.0012      0.001     -1.322      0.186      -0.003       0.001
BMI                          0.0897      0.015      5.945      0.000       0.060       0.119
DiabetesPedigreeFunction     0.9452      0.299      3.160      0.002       0.359       1.531
Age                          0.0149      0.009      1.593      0.111      -0.003       0.033
============================================================================================
"""

* **Insulin** ที่ผลออกมาว่าไม่ส่งผลต่อโรคเบาหวานนั้น อาจจะเกิดจากความไม่สมบูรณ์ของข้อมูล ที่มี missing value อยู่มาก 

In [14]:
model.params

Intercept                  -8.404696
Pregnancies                 0.123182
Glucose                     0.035164
BloodPressure              -0.013296
SkinThickness               0.000619
Insulin                    -0.001192
BMI                         0.089701
DiabetesPedigreeFunction    0.945180
Age                         0.014869
dtype: float64

In [16]:
model.predict(x)

0      0.721727
1      0.048642
2      0.796702
3      0.041625
4      0.902184
5      0.146632
6      0.066578
7      0.644570
8      0.709358
9      0.036336
10     0.219635
11     0.897753
12     0.784430
13     0.628598
14     0.627557
15     0.400893
16     0.371178
17     0.196611
18     0.357505
19     0.234200
20     0.392436
21     0.316639
22     0.940424
23     0.294746
24     0.701997
25     0.441283
26     0.737435
27     0.045773
28     0.538999
29     0.277786
         ...   
738    0.163620
739    0.225471
740    0.768611
741    0.167195
742    0.094806
743    0.662213
744    0.930485
745    0.311007
746    0.695348
747    0.311140
748    0.827939
749    0.573959
750    0.545524
751    0.275590
752    0.106005
753    0.665938
754    0.725689
755    0.441711
756    0.480928
757    0.317855
758    0.164099
759    0.902103
760    0.096267
761    0.936088
762    0.087253
763    0.317115
764    0.318969
765    0.170416
766    0.284976
767    0.072014
Length: 768, dtype: floa

In [18]:
model.predict(x).apply(lambda p: 0 if p < .5 else 1)

0      1
1      0
2      1
3      0
4      1
5      0
6      0
7      1
8      1
9      0
10     0
11     1
12     1
13     1
14     1
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     1
23     0
24     1
25     0
26     1
27     0
28     1
29     0
      ..
738    0
739    0
740    1
741    0
742    0
743    1
744    1
745    0
746    1
747    0
748    1
749    1
750    1
751    0
752    0
753    1
754    1
755    0
756    0
757    0
758    0
759    1
760    0
761    1
762    0
763    0
764    0
765    0
766    0
767    0
Length: 768, dtype: int64

In [29]:
model.predict([[1, 5,180,80,35,180,33,0.5,30]])

array([0.76187558])

In [30]:
xx =model.predict([[1, 5,180,80,35,180,33,0.5,30]])
xx

array([0.76187558])

In [34]:
P_negative = 1- xx
P_negative

array([0.23812442])

In [19]:
model.pred_table()

array([[445.,  55.],
       [112., 156.]])

In [20]:
TN, FP, FN, TP = model.pred_table().ravel()

In [21]:
Acurracy=(TP+TN)/(TP+TN+FP+FN)
Acurracy

0.7825520833333334

In [22]:
Precision =(TP)/(TP+FP)
Precision

0.7393364928909952

In [23]:
Recall = (TP)/(TP+FN)
Recall

0.582089552238806

In [24]:
F_measure = 2 * ( Recall*Precision) / (Recall+Precision)
F_measure

0.651356993736952